seed: 42

output:
  base_dir: outputs
  # run_name: lstm_bilstm_noise

data_dir: ./data
emotions: [happy, sad, normal]
csv_files: [att.csv, med.csv, powerspec.csv, combined.csv, filtered.csv, rawwave.csv, sigqual.csv]
time_steps: 128
min_cols_per_file: 10

split:
  test_size: 0.30
  seed: 42

augment:
  enabled: true
  sad_times: 3
  other_times: 3
  noise:  # 这是加在原始数据上的噪声
    mean: 0.0
    std: 0.01

preprocess:
  impute_strategy: mean
  scale: true
  pca_n_components: 64

# 此处的噪声是加在预处理之后，进入模型之前
gaussian_noise:
  enabled: true
  apply_to: [ae, clf]
  mean: 0.0
  std: 0.01

autoencoder:
  epochs: 100
  batch_size: 32
  val_split: 0.10
  latent_dim: 128
  enc_layers: 2
  enc_units: null
  enc_dropout: 0.25
  use_bidirectional_decoder: true
  dec_units: null
  dec_dropout: 0.25
  lr: 0.001
  lr_patience: 8
  early_stop_patience: 20
  min_lr: 1e-6

sample_stats:
  enabled: true

mixup:
  enabled: true
  alpha: 0.3
  augment_ratio: 1.0

classifier:
  mode: bilstm
  epochs: 200
  batch_size: 16
  val_split: 0.20
  initial_lr: 0.001
  use_cosine_decay: true
  lr_patience: 10
  early_stop_patience: 30
  min_lr: 1e-6

  # 这是双向LSTM的参数
  lstm_units: 128
  num_layers: 2
  dropout: 0.35
  recurrent_dropout: 0.0
  pooling: avgmax
  label_smoothing: 0.05
